# Generated by Django 4.2.13 on 2025-09-19 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ManageServerConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(help_text='IP-адрес терминала, например 46.19.66.141', max_length=100)),
                ('port', models.IntegerField(default=5001, help_text='Порт терминала, например 5001')),
                ('type', models.CharField(default='CW', help_text='Тип сервера (например CW, TEST, BACKUP)', max_length=50)),
            ],
            options={
                'verbose_name': 'Настройки API системы мониторинга',
                'verbose_name_plural': 'Настройки API системы мониторинга',
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название программы', max_length=100)),
                ('price', models.DecimalField(decimal_places=2, help_text='Цена программы', max_digits=10)),
                ('description', models.TextField(blank=True, help_text='Описание программы', null=True)),
                ('duration', models.PositiveIntegerField(default=0, help_text='Продолжительность мойки (мин)')),
                ('id_service', models.PositiveIntegerField(default=0, help_text='Идентификатор программы DScloud')),
            ],
            options={
                'verbose_name': 'Программа мойки',
                'verbose_name_plural': 'Программы мойки',
            },
        ),
        migrations.CreateModel(
            name='ReceiptServerConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(help_text='IP:PORT кассы, например 192.168.0.10:5000', max_length=100)),
            ],
            options={
                'verbose_name': 'Настройки API печати чеков',
                'verbose_name_plural': 'Настройки API печати чеков',
            },
        ),
        migrations.CreateModel(
            name='TerminalStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.PositiveIntegerField(default=0, help_text='ID робота в системе DScloud')),
                ('car_wash_identifier', models.PositiveIntegerField(default=0, help_text='ID мойки в системе DScloud')),
                ('name', models.CharField(help_text='Название робота', max_length=100)),
                ('mobile_app_qr_code', models.TextField(blank=True, help_text='Статический QR-код для перехода в старое мобильное приложение')),
                ('bay_number', models.PositiveIntegerField(verbose_name='Номер поста')),
                ('gvl_cardnum', models.IntegerField(default=0)),
                ('gvl_cardsum', models.IntegerField(default=0)),
                ('gvl_sum', models.IntegerField(default=0)),
                ('gvl_err', models.IntegerField(default=0)),
                ('gvl_time', models.IntegerField(default=0)),
                ('gvl_source', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Terminal Status DScloud',
                'verbose_name_plural': 'Terminal Statuses DScloud',
            },
        ),
        migrations.CreateModel(
            name='VendotekServerConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(help_text='IP-адрес терминала, например 192.168.53.186', max_length=100)),
                ('port', models.IntegerField(default=62801, help_text='Порт терминала, например 62801')),
            ],
            options={
                'verbose_name': 'Настройки API Vendotek',
                'verbose_name_plural': 'Настройки API Vendotek',
            },
        ),
        migrations.CreateModel(
            name='WashSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delay_between_washes', models.PositiveIntegerField(default=5, help_text='Задержка перед запуском следующей мойки (в секундах)')),
            ],
            options={
                'verbose_name': 'Настройки таймера между мойками',
                'verbose_name_plural': 'Настройки таймера между мойками',
            },
        ),
        migrations.CreateModel(
            name='WashOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_price', models.DecimalField(decimal_places=2, help_text='Цена программы мойки', max_digits=8)),
                ('transaction_id', models.CharField(help_text='ID транзакции', max_length=100, unique=True)),
                ('date', models.DateTimeField(auto_now_add=True, help_text='Дата и время создания')),
                ('status', models.CharField(choices=[('created', 'Created'), ('waiting_payment', 'Waiting Payment'), ('payed', 'Payed'), ('failed', 'Failed'), ('completed', 'Completed'), ('processing', 'Processing'), ('mobile_qr_request', 'Mobile Qr Request')], default='created', help_text='Статус заказа', max_length=50)),
                ('ucn', models.CharField(blank=True, help_text='Номер карты лояльности', max_length=50, null=True)),
                ('payment_type', models.CharField(blank=True, choices=[('bank_card', 'Bank Card'), ('cash', 'Cash'), ('mobile_app', 'Mobile App'), ('loyalty_card', 'Loyalty Card')], help_text='Тип оплаты', max_length=20, null=True)),
                ('queue_position', models.PositiveIntegerField(blank=True, help_text='Позиция в очереди (Первый, второй, и т.д.)', null=True)),
                ('queue_number', models.CharField(blank=True, help_text='Статичный номер в очереди (например, A-1)', max_length=20, null=True)),
                ('qr_code', models.TextField(blank=True, null=True)),
                ('gvl_source', models.IntegerField(blank=True, null=True)),
                ('is_mobile_payment', models.BooleanField(default=False, help_text='Оплата через мобильное приложение да/нет')),
                ('program', models.ForeignKey(help_text='Название программы мойки', on_delete=django.db.models.deletion.CASCADE, to='orders.program')),
            ],
            options={
                'verbose_name': 'Таблица заказов',
                'verbose_name_plural': 'Таблица заказов',
            },
        ),
    ]
