# Generated by Django 5.2.4 on 2025-07-21 12:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название программы', max_length=100)),
                ('duration', models.PositiveIntegerField(help_text='Длительность в секундах')),
                ('price', models.DecimalField(decimal_places=2, help_text='Цена в рублях', max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Terminal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название терминала', max_length=100)),
                ('location', models.CharField(blank=True, help_text='Местоположение терминала', max_length=255, null=True)),
                ('ip_address', models.GenericIPAddressField(help_text='IP-адрес терминала')),
            ],
        ),
        migrations.CreateModel(
            name='Robot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='idle', help_text='Текущий статус робота', max_length=50)),
                ('terminal', models.OneToOneField(help_text='Привязанный терминал', on_delete=django.db.models.deletion.CASCADE, to='orders.terminal')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Уникальный идентификатор заказа', primary_key=True, serialize=False)),
                ('car_number', models.CharField(help_text='Госномер автомобиля', max_length=20)),
                ('payment_status', models.CharField(choices=[('created', 'Создан'), ('payment_pending', 'Ожидание оплаты'), ('paid', 'Оплачен')], default='created', help_text='Статус оплаты', max_length=20)),
                ('execution_status', models.CharField(choices=[('queue', 'В очереди'), ('in_progress', 'Выполняется'), ('completed', 'Завершён'), ('cancelled', 'Отменён'), ('failed', 'Ошибка')], default='queue', help_text='Статус выполнения', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата и время создания заказа')),
                ('program', models.ForeignKey(help_text='Выбранная программа мойки', on_delete=django.db.models.deletion.CASCADE, to='orders.program')),
                ('robot', models.ForeignKey(blank=True, help_text='Робот, выполняющий заказ', null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.robot')),
                ('terminal', models.ForeignKey(help_text='Терминал, через который оформлен заказ', on_delete=django.db.models.deletion.CASCADE, to='orders.terminal')),
            ],
        ),
    ]
