# Generated by Django 4.2.13 on 2025-09-30 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='plc_start_write_address',
            field=models.PositiveIntegerField(default=0, help_text='Адрес для старта программы в PLC'),
        ),
    ]
