# Generated by Django 4.2.13 on 2025-09-18 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendotekServerConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(help_text='IP-адрес терминала, например 192.168.53.186', max_length=100)),
                ('port', models.IntegerField(default=62801, help_text='Порт терминала, например 62801')),
            ],
            options={
                'verbose_name': 'Настройки API Vendotek',
                'verbose_name_plural': 'Настройки API Vendotek',
            },
        ),
    ]
