# Generated by Django 5.2.4 on 2025-07-21 12:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='car_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='execution_status',
            field=models.CharField(choices=[('queue', 'В очереди'), ('in_progress', 'В процессе'), ('completed', 'Завершен'), ('cancelled', 'Отменен'), ('failed', 'Ошибка')], default='queue', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('created', 'Создан'), ('payment_pending', 'Ожидание оплаты'), ('paid', 'Оплачен')], default='created', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.program'),
        ),
        migrations.AlterField(
            model_name='order',
            name='robot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.robot'),
        ),
        migrations.AlterField(
            model_name='order',
            name='terminal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.terminal'),
        ),
        migrations.AlterField(
            model_name='program',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='program',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='robot',
            name='status',
            field=models.CharField(default='idle', max_length=50),
        ),
        migrations.AlterField(
            model_name='robot',
            name='terminal',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='orders.terminal'),
        ),
        migrations.AlterField(
            model_name='terminal',
            name='ip_address',
            field=models.GenericIPAddressField(),
        ),
        migrations.AlterField(
            model_name='terminal',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='terminal',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
