# Generated by Django 4.2.13 on 2025-09-25 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='manageserverconfig',
            name='loyalty_status',
            field=models.BooleanField(default=False, help_text='Система лояльности для работы с картой'),
        ),
        migrations.AlterField(
            model_name='manageserverconfig',
            name='type',
            field=models.CharField(default='CW', help_text='Тип сервера (например CW, ONVI)', max_length=50),
        ),
        migrations.AlterField(
            model_name='program',
            name='lty_price',
            field=models.DecimalField(decimal_places=2, help_text='Цена программы по лояльности', max_digits=10, null=True),
        ),
    ]
