# Generated by Django 4.2.13 on 2026-01-16 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_terminalstatus_led_board'),
    ]

    operations = [
        migrations.AddField(
            model_name='terminalstatus',
            name='queue_availability',
            field=models.BooleanField(default=False, help_text='Наличие очереди'),
        ),
        migrations.AlterField(
            model_name='terminalstatus',
            name='led_board',
            field=models.BooleanField(default=False, help_text='Наличие LED табло'),
        ),
        migrations.AlterField(
            model_name='terminalstatus',
            name='loyalty_status',
            field=models.BooleanField(default=False, help_text='Наличие системы лояльности'),
        ),
        migrations.AlterField(
            model_name='washorder',
            name='amount_sum',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='washorder',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='washorder',
            name='is_mobile_payment',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='washorder',
            name='payment_type',
            field=models.CharField(blank=True, choices=[('bank_card', 'Банковская карта'), ('cash', 'Наличные'), ('mobile_app', 'Мобильное приложение'), ('loyalty_card', 'Карта лояльности')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='washorder',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.program'),
        ),
        migrations.AlterField(
            model_name='washorder',
            name='program_price',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='washorder',
            name='queue_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='washorder',
            name='queue_position',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='washorder',
            name='status',
            field=models.CharField(choices=[('created', 'Создан'), ('waiting_payment', 'Ожидание оплаты'), ('payed', 'Оплачен'), ('failed', 'Ошибка оплаты'), ('canceled', 'Отменён'), ('completed', 'Завершён'), ('processing', 'В процессе'), ('mobile_qr_request', 'Запрос QR мобильного приложения')], default='created', max_length=50),
        ),
        migrations.AlterField(
            model_name='washorder',
            name='transaction_id',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='washorder',
            name='ucn',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
