# Generated by Django 5.2.4 on 2025-07-24 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_car_number_alter_order_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='robot',
            name='terminal',
        ),
        migrations.RemoveField(
            model_name='program',
            name='duration',
        ),
        migrations.CreateModel(
            name='WashOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('transaction_id', models.CharField(max_length=100, unique=True)),
                ('date', models.CharField(max_length=30)),
                ('status', models.CharField(choices=[('created', 'Created'), ('payment_processing', 'Payment Processing'), ('waiting_payment', 'Waiting Payment'), ('payment_authorized', 'Payment Authorized'), ('payed', 'Payed'), ('failed', 'Failed'), ('completed', 'Completed'), ('canceled', 'Canceled'), ('refunded', 'Refunded'), ('free_processing', 'Free Processing')], default='created', max_length=50)),
                ('ucn', models.CharField(blank=True, max_length=50, null=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.program')),
            ],
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Robot',
        ),
        migrations.DeleteModel(
            name='Terminal',
        ),
    ]
