# Generated by Django 5.2.4 on 2025-07-25 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_robot_terminal_remove_program_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='description',
            field=models.TextField(blank=True, help_text='Описание программы', null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='duration',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Продолжительность в минутах'),
            preserve_default=False,
        ),
    ]
