# Generated by Django 4.2.13 on 2025-09-23 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_add_functions_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='functions',
            field=models.TextField(blank=True, help_text='Функции программы (через запятую)', null=True),
        ),
    ]
