# Generated by Django 4.2.13 on 2026-04-20 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_terminalstatus_queue_availability_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='end_time_lty_price',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='start_time_lty_price',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='duration',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='program',
            name='functions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='id_service',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='program',
            name='is_visibility',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='program',
            name='lty_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='program',
            name='plc_start_write_address',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='program',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='program',
            name='promo_value',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='washorder',
            name='payment_type',
            field=models.CharField(blank=True, choices=[('bank_card', 'Банковская карта'), ('cash', 'Наличные'), ('mobile_app', 'Мобильное приложение'), ('loyalty_card', 'Карта лояльности'), ('opti', 'OPTI')], max_length=20, null=True),
        ),
    ]
