# Generated by Django 5.2.4 on 2025-07-25 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_program_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='duration',
            field=models.PositiveIntegerField(default=0, help_text='Продолжительность в минутах'),
        ),
    ]
