# Generated by Django 5.2.4 on 2025-07-25 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_program_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='washorder',
            name='payment_type',
            field=models.CharField(blank=True, choices=[('bank-card', 'Bank Card'), ('cash', 'Cash'), ('mobile-app', 'Mobile App'), ('loyalty-card', 'Loyalty Card')], help_text='Тип оплаты: bank-card, cash, mobile-app, loyalty-card', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='washorder',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('waiting_payment', 'Waiting Payment'), ('payed', 'Payed'), ('failed', 'Failed'), ('completed', 'Completed'), ('processing', 'Processing')], default='created', max_length=50),
        ),
    ]
