# Generated by Django 5.2.4 on 2025-07-26 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_washorder_payment_type_alter_washorder_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='TerminalStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('bay_number', models.IntegerField()),
                ('gvl_cardnum', models.IntegerField()),
                ('gvl_cardsum', models.IntegerField()),
                ('gvl_sum', models.IntegerField()),
                ('gvl_err', models.IntegerField()),
                ('gvl_time', models.IntegerField()),
                ('gvl_source', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='washorder',
            name='payment_type',
            field=models.CharField(blank=True, choices=[('bank-card', 'Bank Card'), ('cash', 'Cash'), ('mobile-app', 'Mobile App'), ('loyalty-card', 'Loyalty Card')], help_text='Тип оплаты', max_length=20, null=True),
        ),
    ]
