# Generated by Django 5.2.4 on 2025-07-26 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_terminalstatus_alter_washorder_payment_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='terminalstatus',
            options={'verbose_name': 'Terminal status', 'verbose_name_plural': 'Terminal statuses'},
        ),
    ]
