# Generated by Django 5.2.4 on 2025-07-28 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_alter_terminalstatus_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='washorder',
            name='queue_number',
            field=models.CharField(blank=True, help_text='Номер в очереди, например A-1', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='washorder',
            name='queue_position',
            field=models.PositiveIntegerField(blank=True, help_text='Порядковый номер в очереди', null=True),
        ),
    ]
