# Generated by Django 5.2.4 on 2025-07-28 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_washorder_queue_number_washorder_queue_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='washorder',
            name='queue_number',
            field=models.CharField(blank=True, help_text='Статичный номер в очереди (например, A-1)', null=True),
        ),
    ]
