# Generated by Django 5.2.4 on 2025-07-29 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_alter_washorder_queue_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='WashSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delay_between_washes', models.PositiveIntegerField(default=5, help_text='Задержка перед запуском следующей мойки (в секундах)')),
            ],
            options={
                'verbose_name': 'Настройки мойки',
                'verbose_name_plural': 'Настройки мойки',
            },
        ),
    ]
