# Generated by Django 5.2.4 on 2025-07-30 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_washsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceiptServerConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(help_text='IP:PORT кассы, например 192.168.0.10:5000', max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='washorder',
            name='qr_code',
            field=models.TextField(blank=True, help_text='QR-код', null=True),
        ),
    ]
