# Generated by Django 5.2.4 on 2025-07-30 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_receiptserverconfig_washorder_qr_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='receiptserverconfig',
            options={'verbose_name': 'Настройки API печати чеков', 'verbose_name_plural': 'Настройки мойки'},
        ),
    ]
