# Generated by Django 5.2.4 on 2025-08-04 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_alter_receiptserverconfig_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='program',
            options={'verbose_name': 'Программа мойки', 'verbose_name_plural': 'Программы мойки'},
        ),
        migrations.AlterModelOptions(
            name='terminalstatus',
            options={'verbose_name': 'Статус терминала для DScloud', 'verbose_name_plural': 'Статусы терминала для DScloud'},
        ),
        migrations.AlterModelOptions(
            name='washorder',
            options={'verbose_name': 'Заказ на мойку', 'verbose_name_plural': 'Заказы на мойку'},
        ),
        migrations.AddField(
            model_name='program',
            name='id_service',
            field=models.PositiveIntegerField(default=0, help_text='идентификатор программы DScloud', verbose_name='ID сервиса в DScloud'),
        ),
        migrations.AddField(
            model_name='terminalstatus',
            name='car_wash_identifier',
            field=models.PositiveIntegerField(default=0, help_text='Идентификатор этой мойки в системе DScloud для пинга цен', verbose_name='Идентификатор мойки в DScloud'),
        ),
        migrations.AlterField(
            model_name='program',
            name='duration',
            field=models.PositiveIntegerField(default=0, help_text='Длительность в минутах', verbose_name='Длительность (мин)'),
        ),
        migrations.AlterField(
            model_name='program',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название программы'),
        ),
        migrations.AlterField(
            model_name='program',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='terminalstatus',
            name='bay_number',
            field=models.PositiveIntegerField(verbose_name='Номер бокса'),
        ),
        migrations.AlterField(
            model_name='terminalstatus',
            name='gvl_cardnum',
            field=models.IntegerField(default=0, verbose_name='Номер карты (GVLCardNum)'),
        ),
        migrations.AlterField(
            model_name='terminalstatus',
            name='gvl_cardsum',
            field=models.IntegerField(default=0, verbose_name='Сумма по карте (GVLCardSum)'),
        ),
        migrations.AlterField(
            model_name='terminalstatus',
            name='gvl_err',
            field=models.IntegerField(default=0, verbose_name='Код ошибки (GVLErr)'),
        ),
        migrations.AlterField(
            model_name='terminalstatus',
            name='gvl_source',
            field=models.IntegerField(default=0, verbose_name='Источник (GVLSource)'),
        ),
        migrations.AlterField(
            model_name='terminalstatus',
            name='gvl_sum',
            field=models.IntegerField(default=0, verbose_name='Общая сумма (GVLSum)'),
        ),
        migrations.AlterField(
            model_name='terminalstatus',
            name='gvl_time',
            field=models.IntegerField(default=0, verbose_name='Время (GVLTime)'),
        ),
        migrations.AlterField(
            model_name='terminalstatus',
            name='identifier',
            field=models.PositiveIntegerField(verbose_name='Идентификатор терминала'),
        ),
        migrations.AlterField(
            model_name='terminalstatus',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Имя терминала'),
        ),
        migrations.AlterField(
            model_name='washorder',
            name='date',
            field=models.CharField(max_length=30, verbose_name='Дата и время создания'),
        ),
        migrations.AlterField(
            model_name='washorder',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.program', verbose_name='Программа'),
        ),
        migrations.AlterField(
            model_name='washorder',
            name='program_price',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Цена на момент заказа'),
        ),
        migrations.AlterField(
            model_name='washorder',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('waiting_payment', 'Waiting Payment'), ('payed', 'Payed'), ('failed', 'Failed'), ('completed', 'Completed'), ('processing', 'Processing')], default='created', max_length=50, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='washorder',
            name='transaction_id',
            field=models.CharField(max_length=100, unique=True, verbose_name='ID транзакции'),
        ),
        migrations.AlterField(
            model_name='washorder',
            name='ucn',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Номер карты лояльности'),
        ),
    ]
