# Generated by Django 5.2.4 on 2025-08-04 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_alter_program_options_alter_terminalstatus_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='terminalstatus',
            options={'verbose_name': 'Terminal Status DScloud', 'verbose_name_plural': 'Terminal Statuses DScloud'},
        ),
        migrations.AlterModelOptions(
            name='washorder',
            options={'verbose_name': 'Таблица заказов', 'verbose_name_plural': 'Таблица заказов'},
        ),
        migrations.AlterModelOptions(
            name='washsettings',
            options={'verbose_name': 'Настройки таймера между мойками', 'verbose_name_plural': 'Настройки таймера между мойками'},
        ),
        migrations.AlterField(
            model_name='program',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='duration',
            field=models.PositiveIntegerField(default=0, help_text='Длительность в минутах'),
        ),
        migrations.AlterField(
            model_name='program',
            name='id_service',
            field=models.PositiveIntegerField(default=0, help_text='идентификатор программы DScloud'),
        ),
        migrations.AlterField(
            model_name='program',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='program',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='terminalstatus',
            name='bay_number',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='terminalstatus',
            name='car_wash_identifier',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='terminalstatus',
            name='gvl_cardnum',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='terminalstatus',
            name='gvl_cardsum',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='terminalstatus',
            name='gvl_err',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='terminalstatus',
            name='gvl_source',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='terminalstatus',
            name='gvl_sum',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='terminalstatus',
            name='gvl_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='terminalstatus',
            name='identifier',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='terminalstatus',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='washorder',
            name='date',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='washorder',
            name='payment_type',
            field=models.CharField(blank=True, choices=[('bank-card', 'Bank Card'), ('cash', 'Cash'), ('mobile-app', 'Mobile App'), ('loyalty-card', 'Loyalty Card')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='washorder',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.program'),
        ),
        migrations.AlterField(
            model_name='washorder',
            name='program_price',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='washorder',
            name='qr_code',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='washorder',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('waiting_payment', 'Waiting Payment'), ('payed', 'Payed'), ('failed', 'Failed'), ('completed', 'Completed'), ('processing', 'Processing')], default='created', max_length=50),
        ),
        migrations.AlterField(
            model_name='washorder',
            name='transaction_id',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='washsettings',
            name='delay_between_washes',
            field=models.PositiveIntegerField(default=5, help_text='Задержка перед запуском следующей мойки (в секундах)', verbose_name='Задержка перед запуском следующей мойки (в секундах)'),
        ),
    ]
