# Generated by Django 5.2.4 on 2025-08-04 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_alter_terminalstatus_options_alter_washorder_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='washorder',
            name='queue_number',
            field=models.CharField(blank=True, help_text='Статичный номер в очереди (например, A-1)', null=True, verbose_name='номер в очереди (например, A-1)'),
        ),
        migrations.AlterField(
            model_name='washorder',
            name='queue_position',
            field=models.PositiveIntegerField(blank=True, help_text='Позиция в очереди', null=True, verbose_name='Позиция в очереди'),
        ),
    ]
