# Generated by Django 5.2.4 on 2025-08-04 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_alter_washorder_queue_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='washorder',
            name='gvl_source',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='washorder',
            name='payment_type',
            field=models.CharField(blank=True, choices=[('bank_card', 'Bank Card'), ('cash', 'Cash'), ('mobile_app', 'Mobile App'), ('loyalty_card', 'Loyalty Card')], max_length=20, null=True),
        ),
    ]
