# Generated by Django 5.2.4 on 2025-08-05 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_washorder_gvl_source_alter_washorder_payment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='washorder',
            name='is_mobile_payment',
            field=models.BooleanField(default=False, verbose_name='Оплата через мобильное приложение'),
        ),
        migrations.AlterField(
            model_name='washorder',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания'),
        ),
        migrations.AlterField(
            model_name='washorder',
            name='transaction_id',
            field=models.UUIDField(unique=True, verbose_name='ID транзакции'),
        ),
    ]
