# Generated by Django 5.2.4 on 2025-08-05 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0020_washorder_is_mobile_payment_alter_washorder_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='washorder',
            name='transaction_id',
            field=models.CharField(max_length=100, unique=True, verbose_name='ID транзакции'),
        ),
    ]
