# Generated by Django 5.2.4 on 2025-08-08 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0021_alter_washorder_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='terminalstatus',
            name='mobile_app_qr_code',
            field=models.TextField(blank=True, help_text='Статический QR-код для перехода в старое мобильное приложение', verbose_name='QR-код для  мобильной оплаты'),
        ),
        migrations.AlterField(
            model_name='washorder',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('waiting_payment', 'Waiting Payment'), ('payed', 'Payed'), ('failed', 'Failed'), ('completed', 'Completed'), ('processing', 'Processing'), ('mobile_qr_request', 'Mobile Qr Request')], default='created', max_length=50),
        ),
    ]
