# Generated by Django 5.2.4 on 2025-08-08 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0022_terminalstatus_mobile_app_qr_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='description',
            field=models.TextField(blank=True, help_text='Описание программы', null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='duration',
            field=models.PositiveIntegerField(default=0, help_text='Продолжительность мойки (мин)'),
        ),
        migrations.AlterField(
            model_name='program',
            name='id_service',
            field=models.PositiveIntegerField(default=0, help_text='Идентификатор программы DScloud'),
        ),
        migrations.AlterField(
            model_name='program',
            name='name',
            field=models.CharField(help_text='Название программы', max_length=100),
        ),
        migrations.AlterField(
            model_name='program',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Цена программы', max_digits=10),
        ),
        migrations.AlterField(
            model_name='terminalstatus',
            name='bay_number',
            field=models.PositiveIntegerField(verbose_name='Номер поста'),
        ),
        migrations.AlterField(
            model_name='terminalstatus',
            name='car_wash_identifier',
            field=models.PositiveIntegerField(default=0, help_text='ID мойки в системе DScloud'),
        ),
        migrations.AlterField(
            model_name='terminalstatus',
            name='identifier',
            field=models.PositiveIntegerField(default=0, help_text='ID робота в системе DScloud'),
        ),
        migrations.AlterField(
            model_name='terminalstatus',
            name='mobile_app_qr_code',
            field=models.TextField(blank=True, help_text='Статический QR-код для перехода в старое мобильное приложение'),
        ),
        migrations.AlterField(
            model_name='terminalstatus',
            name='name',
            field=models.CharField(help_text='Название робота', max_length=100),
        ),
        migrations.AlterField(
            model_name='washorder',
            name='date',
            field=models.DateTimeField(auto_now_add=True, help_text='Дата и время создания'),
        ),
        migrations.AlterField(
            model_name='washorder',
            name='is_mobile_payment',
            field=models.BooleanField(default=False, help_text='Оплата через мобильное приложение да/нет'),
        ),
        migrations.AlterField(
            model_name='washorder',
            name='payment_type',
            field=models.CharField(blank=True, choices=[('bank_card', 'Bank Card'), ('cash', 'Cash'), ('mobile_app', 'Mobile App'), ('loyalty_card', 'Loyalty Card')], help_text='Тип оплаты', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='washorder',
            name='program',
            field=models.ForeignKey(help_text='Название программы мойки', on_delete=django.db.models.deletion.CASCADE, to='orders.program'),
        ),
        migrations.AlterField(
            model_name='washorder',
            name='program_price',
            field=models.DecimalField(decimal_places=2, help_text='Цена программы мойки', max_digits=8),
        ),
        migrations.AlterField(
            model_name='washorder',
            name='queue_number',
            field=models.CharField(blank=True, help_text='Статичный номер в очереди (например, A-1)', null=True),
        ),
        migrations.AlterField(
            model_name='washorder',
            name='queue_position',
            field=models.PositiveIntegerField(blank=True, help_text='Позиция в очереди (Первый, второй, и т.д.)', null=True),
        ),
        migrations.AlterField(
            model_name='washorder',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('waiting_payment', 'Waiting Payment'), ('payed', 'Payed'), ('failed', 'Failed'), ('completed', 'Completed'), ('processing', 'Processing'), ('mobile_qr_request', 'Mobile Qr Request')], default='created', help_text='Статус заказа', max_length=50),
        ),
        migrations.AlterField(
            model_name='washorder',
            name='transaction_id',
            field=models.CharField(help_text='ID транзакции', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='washorder',
            name='ucn',
            field=models.CharField(blank=True, help_text='Номер карты лояльности', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='washsettings',
            name='delay_between_washes',
            field=models.PositiveIntegerField(default=5, help_text='Задержка перед запуском следующей мойки (в секундах)'),
        ),
    ]
